// <auto-generated />
namespace mvc2019.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Populate_Memberships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Populate_Memberships));
        
        string IMigrationMetadata.Id
        {
            get { return "201910022356579_Populate_Memberships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
